{% set name = "re2" %}
{% set version = "2023-02-01" %}
{% set dotversion = version.replace('-', '.') %}
# switching from C++14 to C++17 unfortunately introduces a different ABI, see #61;
# create a fake version bump so we can migrate the new version safely
{% set abi_bump_version = dotversion.replace('.01', '.02') %}

package:
  name: {{ name|lower }}
  version: {{ abi_bump_version }}

source:
  url: http://github.com/google/{{ name }}/archive/{{ version }}.tar.gz
  sha256: cbce8b7803e856827201a132862e41af386e7afd9cc6d9a9bc7a4fa4d8ddbdde

build:
  number: 0
  detect_binary_files_with_prefix: true
  run_exports:
    - {{ pin_subpackage("re2", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - make
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
  run:

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - libabseil
    - ninja
  files:
    - cmake_test/
  commands:
    - test -f ${PREFIX}/lib/libre2.so  # [linux]
    - test -f ${PREFIX}/lib/libre2.dylib  # [osx]
    - test ! -f ${PREFIX}/lib/libre2.a  # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/re2.pc  # [unix]
    - test -f ${PREFIX}/include/re2/re2.h  # [unix]
    - if not exist %PREFIX%\\Library\\include\\re2\\re2.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\re2.lib exit 1  # [win]
    - if exist %PREFIX%\\Library\\lib\\re2_static.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\re2.dll exit 1  # [win]

    # CMake integration
    - cd cmake_test
    - cmake $CMAKE_ARGS  -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 .  # [unix]
    - cmake %CMAKE_ARGS% -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 .  # [win]
    - cmake --build .
    - ./re2_example    # [unix]
    - re2_example.exe  # [win]

about:
  home: https://github.com/google/re2/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: |
    RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression
    engines like those used in PCRE, Perl, and Python. It is a C++ library.
  dev_url: https://github.com/google/re2/

extra:
  recipe-maintainers:
    - scopatz
    - isuruf
    - wesm
    - xhochy
    - kszucs
    - pitrou
