{% set name = "re2" %}
{% set version = "2023-06-02" %}
{% set dotversion = version.replace('-', '.') %}

# see https://github.com/google/re2/blob/2023-06-01/CMakeLists.txt#L32-L34
# changes more rarely than version
{% set soversion = "11.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ dotversion }}

source:
  url: http://github.com/google/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 4ccdd5aafaa1bcc24181e6dd3581c3eee0354734bb9f3cb4306273ffa434b94f

build:
  number: 0
  detect_binary_files_with_prefix: true
  run_exports:
    - {{ pin_subpackage("re2", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libabseil
  run:

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
  files:
    - cmake_test/
  commands:
    - test -f ${PREFIX}/lib/libre2.so  # [linux]
    - test -f ${PREFIX}/lib/libre2.dylib  # [osx]
    - test ! -f ${PREFIX}/lib/libre2.a  # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/re2.pc  # [unix]
    - test -f ${PREFIX}/include/re2/re2.h  # [unix]
    - if not exist %PREFIX%\\Library\\include\\re2\\re2.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\re2.lib exit 1  # [win]
    - if exist %PREFIX%\\Library\\lib\\re2_static.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\re2.dll exit 1  # [win]

    # test correctness of pkg-config metadata
    - pkg-config --print-errors --exact-version "{{ soversion }}" re2

    # CMake integration
    - cd cmake_test
    - cmake $CMAKE_ARGS  -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 .  # [unix]
    - cmake %CMAKE_ARGS% -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 .  # [win]
    - cmake --build .
    - ./re2_example    # [unix]
    - re2_example.exe  # [win]

about:
  home: https://github.com/google/re2/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: |
    RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression
    engines like those used in PCRE, Perl, and Python. It is a C++ library.
  dev_url: https://github.com/google/re2/

extra:
  recipe-maintainers:
    - h-vetinari
    - scopatz
    - isuruf
    - wesm
    - xhochy
    - kszucs
    - pitrou
